Improve dist/ctp40-rotate

diff --git a/Pi4/dist/ctp40-rotate b/Pi4/dist/ctp40-rotate
--- a/Pi4/dist/ctp40-rotate
+++ b/Pi4/dist/ctp40-rotate
@@ -8,14 +8,13 @@ DISP_FILE="/usr/share/dispsetup.sh"
 function set_matrix {
     printf "Setting matrix: $1 $2 $3 $4 $5 $6\n";
     xinput set-prop "$DEVICE" "libinput Calibration Matrix" $1 $2 $3 $4 $5 $6 0 0 1
-    
+
     printf "Saving touch settings to $UDEV_FILE\n";
     echo "ATTRS{name}==\"Goodix Capacitive TouchScreen\", ENV{LIBINPUT_CALIBRATION_MATRIX}=\"$1 $2 $3 $4 $5 $6\"" | sudo tee $UDEV_FILE > /dev/null
 }
 
 function set_display {
     printf "Rotating display\n";
-    xrandr --output DSI-1 --rotate $1
     sudo python2 - <<EOF
 import os
 import stat
@@ -38,7 +37,22 @@ print("Saving display settings to {}".format(file))
 open(file, 'w').write(data)
 os.chmod(file, stat.S_IRWXU)
 EOF
+    if [ $? -eq 0 ]; then
+        xrandr --output DSI-1 --rotate $1
+        return 0
+    fi
+
+    printf "Failed to set display orientation. Make sure you're running Raspberry Pi OS desktop on a Pi 4.\n"
+    exit 0
 }
+
+printf "This rotate utility only works with the Raspberry Pi OS desktop version.\n"
+
+if [ "$DISPLAY" == "" ]; then
+    printf "You need to set a DISPLAY variable.\n";
+    printf "Try: DISPLAY=:0.0 ctp40-rotate <orientation>\n"
+    exit 0
+fi
 
 if [ "$ORIENTATION" == "right" ]; then
     set_display $ORIENTATION
